name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pn ci

      - name: Lint (pnpm lint)
        run: pn lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pn ci

      - name: Test (pnpm test)
        run: pn test

  test-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pn ci

      - name: Test CLI (pnpm test:cli)
        run: pn test:cli

  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pn ci

      - name: Build (pnpm build)
        run: pn build
