name: Test
on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm ci

      - name: Lint (pnpm lint)
        run: pnpm lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm ci

      - name: Test (pnpm test)
        run: pnpm test

  test-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm ci

      - name: Test CLI (pnpm test:cli)
        run: pnpm test:cli

  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm ci

      - name: Build (pnpm build)
        run: pnpm build
