name: Test

on:
  push:
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: pnpm/action-setup@v6
  #       with:
  #         cache: true

  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: pnpm install & lint
  #       run: |
  #         pnpm install --frozen-lockfile
  #         pnpm lint

  # test:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: pnpm/action-setup@v6
  #       with:
  #         cache: true

  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: pnpm install & test
  #       run: |
  #         pnpm install --frozen-lockfile
  #         pnpm test

  test-cli:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          cache: true

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: pnpm test:cli
        run: pnpm test:cli

  # test-build:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: pnpm/action-setup@v6
  #       with:
  #         cache: true

  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}

  #     - name: pnpm install & build
  #       run: |
  #         pnpm install --frozen-lockfile
  #         pnpm build
